name: Deploy Hexo Blog

on:
  push:
    branches:
      - source  # ← 每次推到 source 分支時自動部署

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Configure Git identity
        run: |
          git config --global user.name 'michaelpig0912'
          git config --global user.email 'michaelpig0912@example.com'

      - name: Deploy Hexo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx hexo clean
          npx hexo generate
          npx hexo deploy
